name: Lint
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  ruff:
    name: Lint
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12.1
          cache: pip
      - name: Run ruff
        run: |
          pip install ruff
          ruff check --output-format=github .
